name: C/C++ CI

on:
  push:
    #tags:
    #  - 'v*'

    #branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        provider: [TFP0, LIBKRW, LIBKERNRW]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Prepare Theos
        uses: Randomblock1/theos-action@v1

      - name: Build package
        run: |
          rm -f packages/*
          cp control.template control
          if [[ ${{matrix.provider}} == TFP0 ]]; then
            USE_TFP0=1 make package FINALPACKAGE=1
          elif [[ ${{matrix.provider}} == LIBKRW ]]; then
            sed -i '' 's/{{.depends}}/libkrw/g' control
            USE_LIBKRW=1 make package FINALPACKAGE=1
          elif [[ ${{matrix.provider}} == LIBKERNRW ]]; then
            sed -i '' 's/{{.depends}}/libkernrw0/g' control
            USE_LIBKERNRW=1 make package FINALPACKAGE=1
          fi
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: fouldecrypt-${{matrix.provider}}
          path: ${{ github.workspace }}/packages/*.deb
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.workspace }}/packages/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
